name: Generate Snake Animation

# Controls when the action will run
on:
  # Runs at 12am UTC every day
  schedule:
    - cron: "0 0 * * *"
  
  # Allows manual workflow run
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches: [ main ]

# Jobs that will run
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake

    steps:
      # Checks out repository
      - uses: actions/checkout@v2
      
      # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: zidanmubarak
          # You can customize colors below
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg
      
      # Push to GitHub
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
